# Generated by Django 5.0.7 on 2024-07-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
