# Generated by Django 5.0.7 on 2024-07-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='default_image/image.jpg', null=True, upload_to='default_image/'),
        ),
    ]
