# Generated by Django 5.0.7 on 2024-07-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
