# Generated by Django 5.0.7 on 2024-07-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='percent',
            field=models.IntegerField(default=20),
        ),
    ]
