# Generated by Django 5.0.7 on 2024-07-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_verificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
