# Generated by Django 5.1 on 2024-08-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_privacypolicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
