# Generated by Django 5.1.1 on 2024-09-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_chatmessage_chatgroups_privatemessagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='pages.userprofile'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='pages.userprofile'),
        ),
        migrations.AlterField(
            model_name='privatemessagemodel',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_prv_messages', to='pages.userprofile'),
        ),
        migrations.AlterField(
            model_name='privatemessagemodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_prv_messages', to='pages.userprofile'),
        ),
    ]
